Module3 task1
htmlacademy-ecmascript/200331-cinemaddict-15 pull request #5
Opened 2021-08-10 22:05 UTC by Gritgritn

2021-08-11 04:13 UTC, what1s1ove requested changes

2021-08-11 04:13 UTC, what1s1ove commented on src/utils.js
> +  return newElement.firstChild;
```suggestion
  return newElement. firstElementChild;
```
firstChild считает пробелы как ребенка. Иногда это может что-то сломать

2021-08-11 04:13 UTC, what1s1ove commented on src/utils.js
> +    case RenderPosition.AFTERBEGIN:
всегда добавляй скобки для кейс блоков

2021-08-11 04:13 UTC, what1s1ove commented on src/view/footerstatistic.js
> +export default FooterStatistic;
```suggestion
export default FooterStatistic;

```

2021-08-11 04:13 UTC, what1s1ove commented on src/view/menu.js
> +export default MenuTemplate;
```suggestion
export default MenuTemplate;

```

2021-08-11 04:13 UTC, what1s1ove commented on src/view/morebtn.js
> +export default ShowmoreBtn;
```suggestion
export default ShowmoreBtn;

```

2021-08-11 04:13 UTC, what1s1ove commented on src/view/no-film.js
> +}
```suggestion
}

```

2021-08-11 04:13 UTC, what1s1ove commented on src/view/sort.js
> +export default SortTemplate;
```suggestion
export default SortTemplate;

```

2021-08-11 04:13 UTC, what1s1ove commented on src/view/usertitle.js
> +export default UserTitle;
```suggestion
export default UserTitle;

```

2021-08-12 04:02 UTC, ZubkoWhatislove requested changes

2021-08-12 04:02 UTC, ZubkoWhatislove commented on src/utils.js
> +    case RenderPosition.AFTERBEGIN:
Неисправен

2021-08-12 12:50 UTC, merged