Module5 task1
htmlacademy-ecmascript/200331-cinemaddict-15 pull request #7
Opened 2021-08-22 00:47 UTC by Gritgritn

2021-08-22 07:34 UTC, what1s1ove requested changes

2021-08-22 07:34 UTC, what1s1ove commented on src/presenter/movie.js
> +    if (evt.key === 'Escape' || evt.key === 'Esc') {
```suggestion
    if (evt.key === KeyboardKey.ESCAPE) {
```
Давай мы для этого тоже енам заведем

2021-08-22 07:34 UTC, what1s1ove commented on src/utils/common.js
> +};
```suggestion
const updateItem = (items, update) => {
  return items.map((it) => it.id === update.id ? update : it);
```
слишком сложно

2021-08-22 07:34 UTC, what1s1ove commented on src/view/flim-listcontainer.js
> +export default class FilmListContainer extends AbstractView {
Экспорты только внизу файла

2021-08-22 07:34 UTC, what1s1ove commented on src/view/mostcommented.js
> +export default class MostCommentedList extends AbstractView {
Экспорты только внизу файла

2021-08-22 07:34 UTC, what1s1ove commented on src/view/toprated.js
> +export default class TopRated extends AbstractView {
Экспорты только внизу файла

2021-08-22 22:06 UTC, Gritgritn commented on src/presenter/movie.js
> +    if (evt.key === 'Escape' || evt.key === 'Esc') {
Линтер говорит, что enum можно только в .ts файлах использовать

2021-08-23 04:54 UTC, what1s1ove requested changes

2021-08-23 04:54 UTC, what1s1ove commented on src/presenter/board.js
> +      case SortType.DATE:
всегда добавляй скобки к кейсам

2021-08-23 04:54 UTC, what1s1ove commented on src/presenter/movie.js
> +    if (evt.key === 'Escape' || evt.key === 'Esc') {
```ts
const SortType = {
  DEFAULT: 'default',
  DATE: 'date-down',
  RATE: 'date-up',
};
```
Так вот же у тебя енам)

2021-08-23 04:54 UTC, what1s1ove commented on src/view/sort.js
> +    if (evt.target.tagName !== 'A') {
проверяй лучше на наличие дата атрибута

2021-08-24 08:14 UTC, what1s1ove requested changes

2021-08-24 08:14 UTC, what1s1ove commented on src/view/sort.js
> +    if (evt.target.tagName === 'data-sort-type') {
не сработает 🥲
нужно проверять на атрибут

2021-08-24 16:12 UTC, what1s1ove approved these changes

2021-08-24 16:12 UTC, what1s1ove commented on src/view/sort.js
> +    const SORT_TYPE_DATA_ATTR = 'data-sort-type';
1. константы должны быть в верху модуля
2. мы можешь заиспользовать эту константу в разметке. Пример я тебе скидывал

2021-08-24 16:12 UTC, what1s1ove commented on src/view/sort.js
> +    const hasAttr = evt.target.hasAttribute('data-sort-type');
```suggestion
    const hasAttr = evt.target.hasAttribute(SORT_TYPE_DATA_ATTR);
```

2021-08-24 16:12 UTC, merged